#!/usr/bin/python

import os, random, time

lines = 100
file_name = time.strftime("%Y-%m-%dT%H%M%S%Z")

f = open(file_name, 'w')

for i in range(0, lines):
        number_list = [random.randint(0, 100) for i in range(0, 4)]
        line = "{0},{1},{2},{3}\n".format(*number_list)
        f.write(line)

f.close()

hdfs_put = "hdfs dfs -put {0} coordinator-example/landing/".format(file_name)
os.system(hdfs_put)
