#!/usr/bin/python

import os, random, time

lines = random.randint(100, 10000)
file_name = time.strftime("%Y-%m-%dT%H%M%S%Z")

f = open(file_name, 'w')

for i in range(0, lines):
	number_list = [random.randint(0, 100) for i in range(0, 5)]
	line = "{0},{1},{2},{3},{4}\n".format(*number_list)
	f.write(line)

f.close()

hdfs_put = "hdfs dfs -put {0} small-file-example/landing/".format(file_name)
os.system(hdfs_put)

os.system("rm {0}".format(file_name)
